name: Ejecutar Colab DGAGRO autom√°ticamente

on:
  schedule:
    - cron: "0 12 * * *"   # 09:00 AM Argentina
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Abrir notebook de Colab para ejecutar todo
        run: |
          curl -L -X GET "https://colab.research.google.com/drive/1QtkTUBCtuoHPUHwhO7AOiqIWmcy_ooBv"
