name: Ejecutar transcriptor DGAGRO360°

on:
  schedule:
    - cron: "0 12 * * *"   # Todos los días 09:00 Argentina
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script
        env:
          GDRIVE_KEY: ${{ secrets.GDRIVE_KEY }}
        run: |
          python script.py
